name: Enfore Merge Order

on:
  pull_request:
    branches: [main]

jobs:
  Check-Source-Branch:
    runs-on: rad-arc-dev-rad000
    permissions:
      pull-requests: read
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Enforce branch promotion order
        uses: actions/github-script@v7
        with:
          script: |
            // get feature branch name
            const headRef = context.payload.pull_request.head.ref;

            // find closed PRs in DEV from the feature branch
            const { data: closedDevPRsFromFeatureBranch } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              base: 'dev',
              head: `${context.repo.owner}:${headRef}`,
              per_page: 50,
            });

            // get PR that was merged into DEV from feature branch
            const mergedDevPRsFromFeatureBranch = closedDevPRsFromFeatureBranch.filter(pr => pr.merged_at !== null);


            // fail if no merged (& closed) PRs found in DEV from feature branch
            if (mergedDevPRsFromFeatureBranch.length === 0) {
              core.setFailed(
                `Failure: Branch "${headRef}" has not been squash-merged into dev. ` +
                `Please merge to dev first before merging to main.`
              );
              return;
            }

            console.log(
              `Success: Branch "${headRef}" was merged to dev before attempting to merge into main.`
            );
        